Use --cgroups=disabled with 'podman run'
Otherwise it fails with:

```
time="2024-05-09T10:07:52Z" level=warning msg="Failed to add conmon to cgroupfs sandbox cgroup: creating cgroup path /libpod_parent/conmon: write /sys/fs/cgroup/cgroup.subtree_control: device or resource busy"
Error: OCI runtime error: crun: the requested cgroup controller `pids` is not available
```

This is with podman 4.9.4+ds1-1.

The issue appeared after GitLab 17 release, which comes with a major
shared runners infra upgrade, cf. [1]. Maybe it's something that will be
fixed, so we'll try to revert this commit at some point in the future.

[1] https://about.gitlab.com/blog/2023/10/04/updating-the-os-version-of-saas-runners-on-linux/